# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"#\n\x0eGetAuthRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\"R\n\x0fGetAuthResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x12\n\ncredential\x18\x03 \x01(\t\x12\x11\n\tclient_id\x18\x04 \x01(\x05\"H\n\x11\x43reateAuthRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x12\n\ncredential\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\x05\" \n\x12\x43reateAuthResponse\x12\n\n\x02id\x18\x01 \x01(\x05\"&\n\x15GetAuthByEmailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"Y\n\x16GetAuthByEmailResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x12\n\ncredential\x18\x03 \x01(\t\x12\x11\n\tclient_id\x18\x04 \x01(\x05\x32\xd2\x01\n\x04\x41uth\x12\x38\n\x07GetAuth\x12\x14.auth.GetAuthRequest\x1a\x15.auth.GetAuthResponse\"\x00\x12\x41\n\nCreateAuth\x12\x17.auth.CreateAuthRequest\x1a\x18.auth.CreateAuthResponse\"\x00\x12M\n\x0eGetAuthByEmail\x12\x1b.auth.GetAuthByEmailRequest\x1a\x1c.auth.GetAuthByEmailResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETAUTHREQUEST']._serialized_start=20
  _globals['_GETAUTHREQUEST']._serialized_end=55
  _globals['_GETAUTHRESPONSE']._serialized_start=57
  _globals['_GETAUTHRESPONSE']._serialized_end=139
  _globals['_CREATEAUTHREQUEST']._serialized_start=141
  _globals['_CREATEAUTHREQUEST']._serialized_end=213
  _globals['_CREATEAUTHRESPONSE']._serialized_start=215
  _globals['_CREATEAUTHRESPONSE']._serialized_end=247
  _globals['_GETAUTHBYEMAILREQUEST']._serialized_start=249
  _globals['_GETAUTHBYEMAILREQUEST']._serialized_end=287
  _globals['_GETAUTHBYEMAILRESPONSE']._serialized_start=289
  _globals['_GETAUTHBYEMAILRESPONSE']._serialized_end=378
  _globals['_AUTH']._serialized_start=381
  _globals['_AUTH']._serialized_end=591
# @@protoc_insertion_point(module_scope)
