# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import favorite_product_pb2 as favorite__product__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in favorite_product_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FavoriteProductStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFavoriteProduct = channel.unary_unary(
                '/product_favorite.FavoriteProduct/CreateFavoriteProduct',
                request_serializer=favorite__product__pb2.CreateFavoriteProductRequest.SerializeToString,
                response_deserializer=favorite__product__pb2.CreateFavoriteProductResponse.FromString,
                _registered_method=True)
        self.ListFavoriteProduct = channel.unary_unary(
                '/product_favorite.FavoriteProduct/ListFavoriteProduct',
                request_serializer=favorite__product__pb2.ListFavoriteProductRequest.SerializeToString,
                response_deserializer=favorite__product__pb2.ListFavoriteProductResponse.FromString,
                _registered_method=True)


class FavoriteProductServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateFavoriteProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFavoriteProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FavoriteProductServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateFavoriteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFavoriteProduct,
                    request_deserializer=favorite__product__pb2.CreateFavoriteProductRequest.FromString,
                    response_serializer=favorite__product__pb2.CreateFavoriteProductResponse.SerializeToString,
            ),
            'ListFavoriteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFavoriteProduct,
                    request_deserializer=favorite__product__pb2.ListFavoriteProductRequest.FromString,
                    response_serializer=favorite__product__pb2.ListFavoriteProductResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product_favorite.FavoriteProduct', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('product_favorite.FavoriteProduct', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FavoriteProduct(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateFavoriteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_favorite.FavoriteProduct/CreateFavoriteProduct',
            favorite__product__pb2.CreateFavoriteProductRequest.SerializeToString,
            favorite__product__pb2.CreateFavoriteProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFavoriteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_favorite.FavoriteProduct/ListFavoriteProduct',
            favorite__product__pb2.ListFavoriteProductRequest.SerializeToString,
            favorite__product__pb2.ListFavoriteProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
