# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: otp.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'otp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\totp.proto\x12\x03otp\"\x1b\n\rGetOTPRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"J\n\x0eGetOTPResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x61uth_id\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\r\n\x05token\x18\x04 \x01(\t\"#\n\x13GetOTPByCodeRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"P\n\x14GetOTPByCodeResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x61uth_id\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\r\n\x05token\x18\x04 \x01(\t\"&\n\x10\x43reateOTPRequest\x12\x12\n\ncredential\x18\x01 \x01(\t\"!\n\x11\x43reateOTPResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"6\n\x12ValidateOTPRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x12\n\ncredential\x18\x02 \x01(\t\"O\n\x13ValidateOTPResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x61uth_id\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\r\n\x05token\x18\x04 \x01(\t2\x83\x02\n\x03OTP\x12\x33\n\x06GetOTP\x12\x12.otp.GetOTPRequest\x1a\x13.otp.GetOTPResponse\"\x00\x12\x45\n\x0cGetOTPByCode\x12\x18.otp.GetOTPByCodeRequest\x1a\x19.otp.GetOTPByCodeResponse\"\x00\x12<\n\tCreateOTP\x12\x15.otp.CreateOTPRequest\x1a\x16.otp.CreateOTPResponse\"\x00\x12\x42\n\x0bValidateOTP\x12\x17.otp.ValidateOTPRequest\x1a\x18.otp.ValidateOTPResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'otp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETOTPREQUEST']._serialized_start=18
  _globals['_GETOTPREQUEST']._serialized_end=45
  _globals['_GETOTPRESPONSE']._serialized_start=47
  _globals['_GETOTPRESPONSE']._serialized_end=121
  _globals['_GETOTPBYCODEREQUEST']._serialized_start=123
  _globals['_GETOTPBYCODEREQUEST']._serialized_end=158
  _globals['_GETOTPBYCODERESPONSE']._serialized_start=160
  _globals['_GETOTPBYCODERESPONSE']._serialized_end=240
  _globals['_CREATEOTPREQUEST']._serialized_start=242
  _globals['_CREATEOTPREQUEST']._serialized_end=280
  _globals['_CREATEOTPRESPONSE']._serialized_start=282
  _globals['_CREATEOTPRESPONSE']._serialized_end=315
  _globals['_VALIDATEOTPREQUEST']._serialized_start=317
  _globals['_VALIDATEOTPREQUEST']._serialized_end=371
  _globals['_VALIDATEOTPRESPONSE']._serialized_start=373
  _globals['_VALIDATEOTPRESPONSE']._serialized_end=452
  _globals['_OTP']._serialized_start=455
  _globals['_OTP']._serialized_end=714
# @@protoc_insertion_point(module_scope)
