# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import otp_pb2 as otp__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in otp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OTPStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOTP = channel.unary_unary(
                '/otp.OTP/GetOTP',
                request_serializer=otp__pb2.GetOTPRequest.SerializeToString,
                response_deserializer=otp__pb2.GetOTPResponse.FromString,
                _registered_method=True)
        self.GetOTPByCode = channel.unary_unary(
                '/otp.OTP/GetOTPByCode',
                request_serializer=otp__pb2.GetOTPByCodeRequest.SerializeToString,
                response_deserializer=otp__pb2.GetOTPByCodeResponse.FromString,
                _registered_method=True)
        self.CreateOTP = channel.unary_unary(
                '/otp.OTP/CreateOTP',
                request_serializer=otp__pb2.CreateOTPRequest.SerializeToString,
                response_deserializer=otp__pb2.CreateOTPResponse.FromString,
                _registered_method=True)
        self.ValidateOTP = channel.unary_unary(
                '/otp.OTP/ValidateOTP',
                request_serializer=otp__pb2.ValidateOTPRequest.SerializeToString,
                response_deserializer=otp__pb2.ValidateOTPResponse.FromString,
                _registered_method=True)


class OTPServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOTPByCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateOTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OTPServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOTP,
                    request_deserializer=otp__pb2.GetOTPRequest.FromString,
                    response_serializer=otp__pb2.GetOTPResponse.SerializeToString,
            ),
            'GetOTPByCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOTPByCode,
                    request_deserializer=otp__pb2.GetOTPByCodeRequest.FromString,
                    response_serializer=otp__pb2.GetOTPByCodeResponse.SerializeToString,
            ),
            'CreateOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOTP,
                    request_deserializer=otp__pb2.CreateOTPRequest.FromString,
                    response_serializer=otp__pb2.CreateOTPResponse.SerializeToString,
            ),
            'ValidateOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateOTP,
                    request_deserializer=otp__pb2.ValidateOTPRequest.FromString,
                    response_serializer=otp__pb2.ValidateOTPResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'otp.OTP', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('otp.OTP', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OTP(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otp.OTP/GetOTP',
            otp__pb2.GetOTPRequest.SerializeToString,
            otp__pb2.GetOTPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOTPByCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otp.OTP/GetOTPByCode',
            otp__pb2.GetOTPByCodeRequest.SerializeToString,
            otp__pb2.GetOTPByCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otp.OTP/CreateOTP',
            otp__pb2.CreateOTPRequest.SerializeToString,
            otp__pb2.CreateOTPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otp.OTP/ValidateOTP',
            otp__pb2.ValidateOTPRequest.SerializeToString,
            otp__pb2.ValidateOTPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
