# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\x12\x06\x63lient\"%\n\x10GetClientRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\"(\n\x17GetClientByEmailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"C\n\x11GetClientResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\x05\"2\n\x13\x43reateClientRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\")\n\x14\x43reateClientResponse\x12\x11\n\tclient_id\x18\x01 \x01(\x05\"E\n\x13UpdateClientRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"F\n\x14UpdateClientResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\x05\"(\n\x13\x44\x65leteClientRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\"\'\n\x14\x44\x65leteClientResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x85\x03\n\x06\x43lient\x12\x42\n\tGetClient\x12\x18.client.GetClientRequest\x1a\x19.client.GetClientResponse\"\x00\x12P\n\x10GetClientByEmail\x12\x1f.client.GetClientByEmailRequest\x1a\x19.client.GetClientResponse\"\x00\x12K\n\x0c\x43reateClient\x12\x1b.client.CreateClientRequest\x1a\x1c.client.CreateClientResponse\"\x00\x12K\n\x0cUpdateClient\x12\x1b.client.UpdateClientRequest\x1a\x1c.client.UpdateClientResponse\"\x00\x12K\n\x0c\x44\x65leteClient\x12\x1b.client.DeleteClientRequest\x1a\x1c.client.DeleteClientResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCLIENTREQUEST']._serialized_start=24
  _globals['_GETCLIENTREQUEST']._serialized_end=61
  _globals['_GETCLIENTBYEMAILREQUEST']._serialized_start=63
  _globals['_GETCLIENTBYEMAILREQUEST']._serialized_end=103
  _globals['_GETCLIENTRESPONSE']._serialized_start=105
  _globals['_GETCLIENTRESPONSE']._serialized_end=172
  _globals['_CREATECLIENTREQUEST']._serialized_start=174
  _globals['_CREATECLIENTREQUEST']._serialized_end=224
  _globals['_CREATECLIENTRESPONSE']._serialized_start=226
  _globals['_CREATECLIENTRESPONSE']._serialized_end=267
  _globals['_UPDATECLIENTREQUEST']._serialized_start=269
  _globals['_UPDATECLIENTREQUEST']._serialized_end=338
  _globals['_UPDATECLIENTRESPONSE']._serialized_start=340
  _globals['_UPDATECLIENTRESPONSE']._serialized_end=410
  _globals['_DELETECLIENTREQUEST']._serialized_start=412
  _globals['_DELETECLIENTREQUEST']._serialized_end=452
  _globals['_DELETECLIENTRESPONSE']._serialized_start=454
  _globals['_DELETECLIENTRESPONSE']._serialized_end=493
  _globals['_CLIENT']._serialized_start=496
  _globals['_CLIENT']._serialized_end=885
# @@protoc_insertion_point(module_scope)
